openapi: 3.0.0
info:
  title: PIX QR Code
  description: |-
    PIX QR Code service API Documentation
  version: '1'

tags:
  - name: Generate QR Code
    description: Generates a QR Code image or "copy-paste" code to allow clients to make a safe deposit
  - name: Get QR Code
    description: Retrieves the payment data previously generated

components:
  parameters:
    'account-id':
      name: account-id
      in: path
      schema:
        type: string
      required: true
      description: Account identifier that will receive the qr code payment. This account id will be defined at onboarding.
    'external-id':
      name: external-id
      in: query
      schema:
        type: string
      required: true
      description: Identifier informed during Generate Qr Code step in order to keep track of the payment process.
  schemas:
    type:
      description: QR Code type that will be generated. At this time we only support DYNAMIC type.
      type: string
      enum:
        - DYNAMIC
    PaymentData:
      type: 'object'
      properties:
        document_id:
          type: 'string'
          description: 'unique identifier for this operation - generated by JD'
        qrcode_image_base64:
          type: 'string'
          description: 'QR Code image file encrypted with base64'
        qrcode_base64:
          type: 'string'
          description: 'copy-paste code encrypted with base64'
        payload_jws:
          type: 'string'
          description: 'signed JWS payload. Its content is retrieved by Get QR Code request in order to provide the needed payment information for the payer'
    QrCode:
      type: object
      properties:
        type:
          description: QR Code type that will be generated. At this time we only support DYNAMIC type.
          type: string
          enum:
            - DYNAMIC
        external_id:
          type: string
          description: 'Client side qr code identifier'
        created_at:
          description: 'date and time when the qr code was created'
          type: string
          format: date-time
        updated_at:
          description: 'date and time when qr code status was changed'
          type: string
          format: date-time
        end_to_end_id:
          description: 'ID generated by PIX network. It will be present after QR Code is payed'
          type: string
        state:
          type: string
          description: 'Actual state for the given QR Code (CREATED, EXPIRED or PAID)'
        amount:
          type: string
          description: 'Payment amount relative to this qr code. Must be greater than 0 with most 2 decimal places'
        receiver:
          type: object
          description: 'copy-paste code encrypted with base64'
          properties:
            pix_key:
              description: The key which identifies the bank account that will receive this payment. It should be requested to be created while onboarding. It can be commonly associated to an e-mail address but can be a cellphone number, a CNPJ or CPF and a randomly generated one.
              type: string
            name:
              description: Name of whom will receive the payment.
              type: string
          required:
            - pix_key
            - name
        expiration:
          description: When this qr code will cease working.
          type: string
          format: date-time
        payer:
          description: Informations about who is paying this qr code. Will be used to match the payment with the qr code being generated.
          type: object
          properties:
            document:
              description: CNPJ or CPF from whom is paying.
              type: string
            name:
              description: First and last name of whom is paying.
              type: string
            city:
              description: City name where the transaction is being made.
              type: string
          required:
            - document
            - name
            - city
    InvalidGeneratePayload:
      type: string
      description: 'JSON payload is not in the correct format'
    InvalidExternalId:
      type: string
      description: 'external id is a required field and must have between 25 and 36 characters (letters and/or numbers only)'
    PayerNotPresent:
      type: string
      description: 'payer name and document number are required fields'
    InvalidPayerDocument:
      type: string
      description: 'payer document must be a valid CPF or CNPJ (only numbers)'
    InvalidAmount:
      type: string
      description: 'amount value must be bigger than zero'
    MissingPixKey:
      type: string
      description: 'pix key is a required field'
    InvalidPayerCity:
      type: string
      description: 'payer city is a required field and must have between 1 and 15 characters (letters only)'
    InvalidReceiverName:
      type: string
      description: 'receiver name is a required field and must have between 1 and 25 characters'
    InvalidExpirationDate:
      type: string
      description: 'expiration date is older than current time'
paths:
  /v1/banking/accounts/{account-id}:
    summary: Banking API root path
    parameters:
      - $ref: '#/components/parameters/account-id'
  /v1/banking/accounts/{account-id}/qrcodes:
    post:
      operationId: CreateDynamicQrCode
      tags:
        - Deposit
      summary: Genererates a dynamic QR Code
      description: 'Generates a QR Code based on data sent by the partner. The given payer must be the same entity to make the payment afterwards'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  anyOf:
                    - $ref: '#/components/schemas/type'
                external_id:
                  type: string
                  description: Client side qr code identifier
                  maximum: 35
                  minimum: 25
                amount:
                  type: number
                  description: Payment amount relative to this qr code. Must be greater than 0 with most 2 decimal places
                  format: double
                  pattern: \d+\.\d{2}
                receiver:
                  description: Informations about whom is receiving this qr code.
                  type: object
                  properties:
                    pix_key:
                      description: The key which identifies the bank account that will receive this payment. It should be requested to be created while onboarding. It can be commonly associated to an e-mail address but can be a cellphone number, a CNPJ or CPF and a randomly generated one.
                      type: string
                      maximum: 77
                      minimum: 1
                    name:
                      description: Name of whom will receive the payment.
                      type: string
                      maximum: 25
                      minimum: 1
                  required:
                    - pix_key
                    - name
                expiration:
                  description: When this qr code will cease working.
                  type: string
                  format: date-time
                payer:
                  description: Informations about who is paying this qr code. Will be used to match the payment with the qr code being generated.
                  type: object
                  properties:
                    document:
                      description: CNPJ or CPF from whom is paying.
                      type: string
                    name:
                      description: First and last name of whom is paying.
                      type: string
                      maximum: 25
                      minimum: 1
                    city:
                      description: City name where the transaction is being made.
                      type: string
                      maximum: 15
                      minimum: 1
                  required:
                    - document
                    - name
                    - city
              required:
                - type
                - external_id
                - amount
                - pix_key
                - receiver
                - payer
                - expiration
      responses:
        '200':
          description: 'QR Code Created. Response retrieves QR Code data for deposit.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentData'
              example:
                document_id: 18f3f977-55dc-4b56-9c7f-2a4b81004051
                qrcode_image_base64: SkQuUElYLlFSQ29kZS5EaW5hbWljbw==
                qrcode_base64: SkQuUElYLlFSQ29kZS5EaW5hbWljbw==
                payload_jws: eyJhbGciOiJQUzUxMiIsImtpZCI6IjUwQTM5Qzc0MUE0RTFDQ...

        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InvalidGeneratePayload'
                  - $ref: '#/components/schemas/InvalidExternalId'
                  - $ref: '#/components/schemas/PayerNotPresent'
                  - $ref: '#/components/schemas/InvalidPayerDocument'
                  - $ref: '#/components/schemas/InvalidAmount'
                  - $ref: '#/components/schemas/MissingPixKey'
                  - $ref: '#/components/schemas/InvalidPayerCity'
                  - $ref: '#/components/schemas/InvalidReceiverName'
                  - $ref: '#/components/schemas/InvalidExpirationDate'
                example:
                  error: 'error while validating generate qrcode request payload: Code: INVALID_PAYER, Message: payer name and document number are required fields'
        '404':
          description: Pix key does not exist
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
              example:
                error: 'error trying to generate qrcode: Code: INVALID_GATEWAY_REQUEST, Message: Chave não localizada!'
        '412':
          description: Qr code with given external id already exists.
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
              example:
                error: 'error trying to add qrcode: Code: EXTERNAL_ID_ALREADY_EXISTS, Message: qrcode with given external id already exists'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
              example:
                error: 'internal server error (context=c125e88b-195e-4579-8077-3946f9cc59a4)'
  /v1/banking/accounts/{account-id}/qrcodes?externalid={external-id}:
    parameters:
      - $ref: '#/components/parameters/external-id'
    get:
      operationId: GetQrCode
      tags:
        - Deposit
      summary: Get a specific QR Code record
      description: 'Get a specific QR Code record according to its external ID'
      responses:
        '200':
          description: 'QR Code is retrieved'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrCode'
              example:
                type: 'DYNAMIC'
                created_at: '2023-11-01T16:02:01.032777Z'
                updated_at: '2023-11-01T16:02:01.032777Z'
                end_to_end_id: 'ASDLFKAJSH0923846123'
                state: 'CREATED'
                value: 10
                external_id: '1611a96f-dd82-469f-b272-6710405842b'
                receiver:
                  pix_key: 'test@ebury.com'
                  name: 'John Doe'
                expiration: '2023-07-12T15:04:05Z'
                payer:
                  document: '12303485412'
                  name: 'Jhon User'
                  city: 'Curitiba'
        '404':
          description: Qr Code not found
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
              example:
                error: 'Code: NOT_FOUND, Message: qrcode not found'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
              example:
                error: 'internal server error (context=c125e88b-195e-4579-8077-3946f9cc59a4)'
